### ISSUE TITLE
Inconsistency between DE factor and gene expression

### ISSUE THREAD

**Issue by YiqunCao** [Oshlack/splatter#65] opened 2019-03-19 04:50 UTC
Hi there,

I simulated 5 continues paths and trying to look at the DE genes among these 5 paths. But the gene expression level seems not consistent with the DE factors. I attached two figures here.

For example, Gene1745, since its DEFacPath1 > 2 and DEFacPath2-5 < 0.3, I thought this gene will be highly expressed in path1 and very lowly expressed in the rest of paths (path2-5). More specifically, since DEFacPath2 = 0.158 and DEFacPath3 = 0.275, this gene should have lower expression in path2 compared to path3.
![Screenshot from 2019-03-19 12-28-42](https://user-images.githubusercontent.com/12710658/54580346-a818b800-4a42-11e9-9edf-6cdb4702c48d.png)

**But when I plotted the log count gene expression bar plot of Gene1745, I saw it is also highly expressed in path2 and even much higher than path3.**
**Could you please help to explain this, or am I understanding something wrongly? Many thanks!**
![image](https://user-images.githubusercontent.com/12710658/54580234-2759bc00-4a42-11e9-8aa4-cf0450835023.png)

**Comment by lazappi** [comment] 2019-03-19 21:31
HI @YiqunCao 

Thanks for giving Splatter a go! If you look at the DE factors Path 1 has the highest factor so I would expect this gene to be most expressed in that path which is what we see. What values did you give the `path.from` parameter? That could explain why the gene is also expressed in Path 2.

**Comment by YiqunCao** [comment] 2019-03-20 06:10
Hi,
I used parameter  path.from=c(0,1,2,3,4). How would this parameter affect the gene expression? Thanks!

**Comment by lazappi** [comment] 2019-03-20 21:45
So by specifying the path like that you have simulated five cell states in a linear trajectory, something like:

```
A -> B -> C -> D -> E
```

The starting point for expression for each step in the path is the end point of the step before. Imagine we had a gene with these DE factors for each step (similar to the gene in your plot):

```
A = 10, B = 2, C = 1, D = 0.5, E = 1
```

If the gene had an underlying mean expression of 2 we would see the following changes in mean expression along each step in the path:

```
A: 2 -> (10 x 2) = 20
B: 20 -> 4
C: 4 -> 2
D: 2 -> 1
E: 1 -> 2
```

This is why you see expression in Path 2 in you example. The gene is starting at a high expression level and decreasing along that part of the path.

Hopefully that clears things up! 😺

**Comment by YiqunCao** [comment] 2019-03-21 03:19
Many thanks for the clear explanation!

Another question, when I try to simulate 10 paths, Path10 is between Path1 and Path2, instead of being after Path9. Is there a way to fix this? Thanks!

**Comment by YiqunCao** [comment] 2019-03-21 03:21
And also, is there a maximum number of paths that can be simulated?

**Comment by lazappi** [comment] 2019-03-22 00:57
There shouldn't be a maximum number of paths but it is possible there is a bug. What parameters did you use to simulate 10 paths and what do you mean by between Path 1 and Path 2?

**Comment by YiqunCao** [comment] 2019-03-22 04:48
I used path.from=0:9 to simulate 10 paths. When I do the PCA plot, Path10 appears between Path1 and 2.
I tried path.from=0:99 to simulate 100 paths, but the PCA plot did not show the continuous layout.

**Comment by lazappi** [comment] 2019-03-24 21:48
I think in this case the problem is with PCA rather than the simulation. These simulations are probably too complex for PCA to show what is going on (at least in the first two dimensions). Something like t-SNE or UMAP might do better but I wouldn't count on it.

**Comment by YiqunCao** [comment] 2019-03-25 05:40
Hi,
I tried Monocle2 as well, Path10 was still between Path1 and 2.
I think it is because of the different order of type numeric and character. "Path10" will be ordered behind "Path1" instead of "Path9" if treated as characters. So in simulation, Path10 is actually simulated after Path9 or Path1?

**Comment by lazappi** [comment] 2019-03-25 21:40
I think you could be right about the ordering. I have opened a new issue (#66) to remind me to check this before the next release.

**Comment by lazappi** [comment] 2019-04-15 06:32
I have fixed the issue of the path orders in the development version. I'm going to close this issue now but feel free to comment/open a new one if you have further questions.

**Closed by lazappi** 2019-04-15 06:32 UTC
